--DROP TABLE Mercaderias.INVENTARIO
CREATE TABLE Mercaderias.INVENTARIO
(
	Id INT IDENTITY PRIMARY KEY NOT NULL
	,Codigo VARCHAR(10) -- NOT NULL
	,Tipo VARCHAR(10) -- NOT NULL
	,Tienda VARCHAR(50) -- NOT NULL
	,FechaInicio DATE -- NOT NULL
	,FechaFin DATE
)
GO

--DROP TABLE Dbo.TIPOS_INVENTARIO_EXT
CREATE TABLE Dbo.TIPOS_INVENTARIO_EXT
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	NombreTipo VARCHAR(10) NOT NULL
)
GO

--DROP TABLE Mercaderias.ARTICULO
CREATE TABLE Mercaderias.ARTICULO
(
	Id INT IDENTITY PRIMARY KEY NOT NULL
	,Codigo VARCHAR(10) -- NOT NULL
	,Stock INT -- NOT NULL
	,IdInventario INT -- NOT NULL
	--,CONSTRAINT fk_Articulo_Id FOREIGN KEY (IdInventario) REFERENCES INVENTARIO (Id)
)
GO

INSERT INTO Dbo.TIPOS_INVENTARIO_EXT VALUES ('TOTAL')
INSERT INTO Dbo.TIPOS_INVENTARIO_EXT VALUES ('PARCIAL')
